### ISSUE TITLE
Update readme examples to reference latest pyenv-action

### ISSUE THREAD

**Issue by nipunn1313** [gabrielfalcao/pyenv-action#136]
Currently, it says
```
gabrielfalcao/pyenv-action@v5
```

Ideally it could say
```
gabrielfalcao/pyenv-action@v7
```

A naive copy paste of the instructions gets you a non latest version (which currently is broken!)

**Comment by gabrielfalcao** [comment]
done in f7e4858f37a5ac86af493047e51b5918b6dfc33e

Thanks for the issue report!
